### ISSUE TITLE
using prepend causes source-maps to no longer work

### ISSUE THREAD

**Issue by toddself** [traducer/browserify-livereload#1]
Since this plugin injects code to the top of the bundle but doesn't adjust the source map it causes the source maps to be 15 lines off.

With live-reload installed:
![image](https://cloud.githubusercontent.com/assets/193412/20365679/ac7e3924-abfc-11e6-811e-6c9a10df0290.png)

Same exact page, plugin disabled:
![image](https://cloud.githubusercontent.com/assets/193412/20365688/b9ef846e-abfc-11e6-8a2b-3b74033bebd4.png)

![image](https://cloud.githubusercontent.com/assets/193412/20365706/c8b49d18-abfc-11e6-9943-2ba6abcec3f9.png)

The second one (without live-reload enabled) points to the correct line of code. Note that in the version using the live-reload plugin the line pointed to doesn't contain a call to `.length`.

**Comment by jacobtipp** [comment]
@toddself I updated the package to create a new sourcemap entirely and offsetting the sourcemap by 15 lines. I tested it briefly, so I'm not positive it works entirely but from what I saw, with debug enabled in browserify, it was debugging the right lines. 

https://github.com/traducer/browserify-livereload/blob/master/lib/index.js#L40-L47

**Comment by toddself** [comment]
hey @traducer sorry i just got a chance to verify this is working correctly!

thank you so much for your help!
